Feature/004 endpoint specs
food2gether/documentation pull request #5
Opened 2024-11-25 19:23 UTC by jogengnagel

Pull Request for Order-Service

2024-11-27 13:25 UTC, Marfien requested changes

2024-11-27 13:25 UTC, Marfien commented on endpoints/orders.md
Ich würde nach wie vor keinen einzelnen Order-Service machen. Hier ist mein gedanke dazu:
Eine Order wird in einer Session (die ein Restaurant zugewiesen hat) gesetzt und ist Quasi teil des Session Objektes, damit wir eine solche Struktur haben (pseudo code):
```javascript
class Session {
    var sessionId: int
    var organizerId: ProfileId
    var orders: Array<Order>
    ...
}

class Order {
    var orderId: int
    var placedBy: ProfileId
    var items: Array<OrderItem>
}

class OrderItem {
    var menuId: int
    var quantity: int
    var extra: string
}
```
Also das eine Order immer fest an ein Session gebunden ist (Kompositions-Beziehung). Ein eigner Service macht hier nur Sinn, wenn keine existenzielle Abhängigkeit besteht (Aggregations-Beziehung)

2024-11-27 14:10 UTC, jogengnagel commented on endpoints/orders.md
Wenn man das aber mit der Kompositionsbeziehung macht, dann hat man ja ohne die Session kein Zugriff auf irgendwelche Orders dieser Session. D.h. wenn man zum Beispiel eine Order-History im Profil einbauen möchte, dann geht das wegen der ExistenzAbhängikeit gar nicht(wenn die Session schon gelöscht wurde) oder nur kompliziert über die einzelnen Sessions. Also würde ich dann auch das Get All  mit Filtern wieder ausbauen. Außerdem (weiß nicht ob das doof ist) hat man auch bei den Abfragen einen folgenden Aufbau .../sessions/:id/orders/:id/. Generell finde ich, dass die Order mehr funktionen / potential in unsere Anwendung als eigener Service hat, als wenn es nur ein teil des Session Services ist.
Wenn du trotzdem sagst, lieber in Session Service einabauen, dann hinterfrag ich das nicht weiter und mach das gelich

2024-11-27 14:13 UTC, jogengnagel commented on endpoints/orders.md
OrderHistory: Oder man könnte das auch machen indem man bei Profile noch ne Liste an Orders einbaut welche immer ergänzt wird, wenn eine neue Order aufgegeben wird. welche man dann als OrderHistory im Profil abfragen könnte.

2024-11-27 14:21 UTC, Marfien commented on endpoints/orders.md
Das ist sowieso nicht teil des MVPs. Ansonsten kann man das auch so machen, dass wir das auch über eine Session-History machen. Man braucht ja sowieso eine irgendeine Referenz auf das Menü, um die Order Sinnvoll dazustellen. Hier macht es dann aber auch mehr Sinn sowas wie ein `OrderSnapshot` am Ende einer Bestellung zu machen, damit Veränderungen an der Speisekarte nicht auch vergangene Bestellung beeinflusst

2024-11-27 15:39 UTC, jogengnagel commented on endpoints/orders.md
Also mach ich das jetzt wieder in die Sessions rein? War ansonsten der Inhalt so in Ordnung?

2024-11-27 16:33 UTC, Marfien commented on endpoints/orders.md
Der Inhalt sieht gut aus. Schau aber gerne nochmal auf die tables. Da sind noch 1-2 Syntax-Fehler im json. Ich hab auch eben noch einmal die Response-Tables durch ChatGPT gejargt, damit die bisschen schöner werden (einfach mit dem Prompt `Please convert this markdown table into html`)

2024-12-05 14:02 UTC, Marfien approved these changes

2024-12-05 14:02 UTC, merged